version: "3"

services:
  vue-app:
    image: node:16.15.0-alpine
    container_name: vue-app-dev
    working_dir: /app
    environment:
      - PATH=/app/node_modules/.bin:$PATH
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command:
      - sh
      - -c
      - |
        yarn install
        yarn serve
